### what is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences
+ NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

+ The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

+ NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

+ A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

#### creating Numpy Arrays

In [1]:
import numpy as np

a = np.array([1,2,3]) # 1D - Vector
print(type(a))
print(a)

b = np.array([[1,2,3],[2,3,3]])
print(b)

<class 'numpy.ndarray'>
[1 2 3]
[[1 2 3]
 [2 3 3]]


In [9]:
# 2D  - Matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# 3D 
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,5,6]]])
print(c)
# 3D - Tensor 

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [4 5 6]]]


In [13]:
# dtype
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [15]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
# with reshape
np.arange(1,10).reshape(3,3)
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
# np.randon
np.random.random((3,4))

array([[0.43049774, 0.50558249, 0.70920338, 0.45418685],
       [0.44143384, 0.32826737, 0.99441898, 0.21393728],
       [0.66626742, 0.74011538, 0.12450974, 0.40367705]])

In [3]:
# np.linspace
import numpy as np
np.linspace(-10,10,10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [57]:
# np.identity
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [63]:
np.arange(81).reshape(3,3,3,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

### Numpy Array Attributes

In [81]:
a1  = np.arange(10,dtype=np.int64)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [67]:
# ndim - number of dimensions 
a3.ndim
a2.ndim

2

In [72]:
# shape 
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [85]:
# itemsize - determines the bit size of the data type
# here a1 data type is int64 so its size is 8
a1.itemsize

8

In [86]:
# dtype - tells the type of any nparray
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int32


#### Changing Datatype

In [92]:
# astype
a3.astype(np.int16)


8

#### Array Operations


In [93]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [98]:
# scalar operations 

#arithmetic
a1 // 2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [104]:
# realtional 
a2>15
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [107]:
# vector operations
# arithemtic 
a1 + a2
a1 ** a2
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

#### Array functions

In [144]:
a1 = np.random.random((3,3))
a2 = np.round(a1*100)
a1

array([[0.84018811, 0.28138039, 0.7901517 ],
       [0.52005112, 0.19663111, 0.26525795],
       [0.43397566, 0.35732781, 0.49538837]])

In [148]:
# max / min / sum / prod
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)

0.00038924721817109275

In [155]:
# 0 -> col and 1 -> row
np.sum(a1,axis = 0)

array([1.79421489, 0.83533932, 1.55079802])

In [158]:
# mean/meadian/ std/ var
np.mean(a1,axis= 1)
np.median(a1,axis=1)
np.std(a1,axis=1)
np.var(a1,axis=1)

array([0.06373533, 0.01935886, 0.00318968])

In [161]:
# trignometric functions
np.sin(a1) # in same way we can calculate all trignomteric functions.

array([[0.74476866, 0.27768202, 0.71046004],
       [0.4969245 , 0.19536647, 0.2621582 ],
       [0.42048124, 0.34977209, 0.47537337]])

In [165]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [167]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[2.31680275, 1.32495751, 2.20373072],
       [1.68211363, 1.21729491, 1.30376723],
       [1.54338131, 1.42950441, 1.64113548]])

In [171]:
# round/floor / ceil
np.ceil(np.random.random((2,3))*100)
# round - round off to nearest integer
# floor - round of to previous number for ex:- 6.9 = 6
# ceil - round off to next number for ex:- 6.1 = 7


array([[99., 23., 69.],
       [90., 97.,  1.]])

##### Indexing and Slicing

In [172]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [173]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
a1[-1]

9

In [176]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [178]:
a2[2,3]

11

In [179]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [181]:
a3[1,0,1]

5

In [182]:
a3[0,1,0]

2

In [183]:
# slicing
a1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
a1[2:5:2]

array([2, 4])

In [186]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [188]:
a2[0,:]

array([0, 1, 2, 3])

In [189]:
a2[:,2]

array([ 2,  6, 10])

In [192]:
a2[1:,1:3]
a2[0:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [193]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [205]:
a2[:2:,1:3:]

array([[1, 2],
       [5, 6]])

In [206]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [209]:
a2[1,::3]

array([4, 7])

In [210]:
a2[:2:,1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [213]:
# 3D array
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [215]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [219]:
a3[0][1]
a3[0,1]

array([3, 4, 5])

In [222]:
a3[1,:,1]

array([10, 13, 16])

In [224]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [229]:
a3[0::2,::5,0::2] # write answer but looks wrong
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

##### Iterating

In [233]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [236]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [237]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [238]:
for i in np.nditer(a3):  # nditer -> converts any dimensional array into 1D array and than iterates on it.
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


##### Reshaping

In [243]:
# reshape
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [246]:
# Transpose
np.transpose(a2)
a2.T  # just using T we can transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [251]:
# ravel -> converts any dimesional array to 1D array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

If we can see the result than it is a temporary operation but if result cannot be seen than it is peramanent operation

##### Stacking

In [258]:
# horizontal stacking
s4 = np.arange(12).reshape(3,4)
s5 = np.arange(12,24).reshape(3,4)
s4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [261]:
np.hstack((s4,s5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [262]:
# vertical stacking
np.vstack((s4,s5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

##### splitting

In [266]:
# horizontal splitting
s4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [269]:
np.hsplit(s4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [272]:
# vertical splitting
np.vsplit(s4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]