In [80]:
# np.sort
# Return a sorted copy of an array.

import numpy as np
a = np.random.randint(1,100,15)
a

array([92, 32, 73, 16, 22, 63, 78, 82, 82, 61, 15, 46, 17, 10, 87])

In [81]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[35, 13, 30, 37],
       [90, 58, 24, 81],
       [13, 33, 92, 16],
       [81, 31, 22, 43],
       [39, 24, 24, 86],
       [70, 55, 52, 21]])

In [82]:
np.sort(a)

array([10, 15, 16, 17, 22, 32, 46, 61, 63, 73, 78, 82, 82, 87, 92])

In [83]:
np.sort(b,axis=0)
# axis value = 0 (sorting column wise)
# axis value = 1 (sorting row wise)

array([[13, 13, 22, 16],
       [35, 24, 24, 21],
       [39, 31, 24, 37],
       [70, 33, 30, 43],
       [81, 55, 52, 81],
       [90, 58, 92, 86]])

In [84]:
# np.append
# The numpy.append() appends the values along the mentioned axis at the end of the array.
np.append(a,200)

array([ 92,  32,  73,  16,  22,  63,  78,  82,  82,  61,  15,  46,  17,
        10,  87, 200])

In [85]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[35., 13., 30., 37.,  1.],
       [90., 58., 24., 81.,  1.],
       [13., 33., 92., 16.,  1.],
       [81., 31., 22., 43.,  1.],
       [39., 24., 24., 86.,  1.],
       [70., 55., 52., 21.,  1.]])

In [86]:
# code 
# np.concatenate
# numpy.concatenate() function concatenate a sequence of arrays along an existing axis.
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [87]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [88]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [89]:
# np.unique 
# with hellp of np.unique() method, we can get the unique values from an array given as paramtere in np.unique() method.
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])


In [90]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [91]:
# np.expand_dims
# with the help of Numpy.expand_dims() method , we can get the expanded dimensions of an array.

a

array([92, 32, 73, 16, 22, 63, 78, 82, 82, 61, 15, 46, 17, 10, 87])

In [92]:
np.expand_dims(a,axis=0)

array([[92, 32, 73, 16, 22, 63, 78, 82, 82, 61, 15, 46, 17, 10, 87]])

In [93]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [94]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [95]:
# np.where
# The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
a

array([92, 32, 73, 16, 22, 63, 78, 82, 82, 61, 15, 46, 17, 10, 87])

In [96]:
# find all indices with value greater than 50.
np.where(a>50)

(array([ 0,  2,  5,  6,  7,  8,  9, 14], dtype=int64),)

In [97]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0, 32,  0, 16, 22,  0,  0,  0,  0,  0, 15, 46, 17, 10,  0])

In [98]:
ayush= np.random.randint(1,1000,10)

In [99]:
print(ayush)
np.where(ayush>=500,26,ayush) 

[628 964 387 429 379 471 822 234 778 793]


array([ 26,  26, 387, 429, 379, 471,  26, 234,  26,  26])

In [100]:
# replace all even numbers with even number.
np.where(a%2==0,0,a)

array([ 0,  0, 73,  0,  0, 63,  0,  0,  0, 61, 15,  0, 17,  0, 87])

In [101]:
# np.argmax
# The numpy.argmax() function returns indices of the max element of the array in a particular axis.
a

array([92, 32, 73, 16, 22, 63, 78, 82, 82, 61, 15, 46, 17, 10, 87])

In [102]:
np.argmax(a)

0

In [103]:
b # for 2d array

array([[35, 13, 30, 37],
       [90, 58, 24, 81],
       [13, 33, 92, 16],
       [81, 31, 22, 43],
       [39, 24, 24, 86],
       [70, 55, 52, 21]])

In [104]:
np.argmax(b,axis=0)

array([1, 1, 2, 4], dtype=int64)

In [105]:
np.argmax(b,axis=1)

array([3, 0, 2, 0, 3, 0], dtype=int64)

In [106]:
# np.argmin
a

array([92, 32, 73, 16, 22, 63, 78, 82, 82, 61, 15, 46, 17, 10, 87])

In [107]:
np.argmin(a)

13

In [108]:
a

array([92, 32, 73, 16, 22, 63, 78, 82, 82, 61, 15, 46, 17, 10, 87])

In [109]:
# np.cumsum
# numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.
np.cumsum(a)

array([ 92, 124, 197, 213, 235, 298, 376, 458, 540, 601, 616, 662, 679,
       689, 776])

In [110]:
b

array([[35, 13, 30, 37],
       [90, 58, 24, 81],
       [13, 33, 92, 16],
       [81, 31, 22, 43],
       [39, 24, 24, 86],
       [70, 55, 52, 21]])

In [111]:
np.cumsum(b,axis=0)

array([[ 35,  13,  30,  37],
       [125,  71,  54, 118],
       [138, 104, 146, 134],
       [219, 135, 168, 177],
       [258, 159, 192, 263],
       [328, 214, 244, 284]])

In [112]:
np.cumsum(b)

array([  35,   48,   78,  115,  205,  263,  287,  368,  381,  414,  506,
        522,  603,  634,  656,  699,  738,  762,  786,  872,  942,  997,
       1049, 1070])

In [113]:
# np.cumprod
a

array([92, 32, 73, 16, 22, 63, 78, 82, 82, 61, 15, 46, 17, 10, 87])

In [114]:
np.cumprod(a)

array([         92,        2944,      214912,     3438592,    75649024,
         470921216, -1922850816,  1240023040, -1397325824,   662470656,
        1347125248,  1838219264,  1184956416, -1035337728,   119930880])

In [115]:
# np.percentile
# numpy.percentile() function used to compute the nth perecentile of the given data (array elements) along the specified axis.
a

array([92, 32, 73, 16, 22, 63, 78, 82, 82, 61, 15, 46, 17, 10, 87])

In [120]:
print(np.percentile(a,50))
print(np.median(a))

61.0
61.0


In [121]:
# np.histogram
# Numpy has a built-in numpy.histogram() function which represent the frequency of data distribution in the graphical form.
print(a)
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

[92 32 73 16 22 63 78 82 82 61 15 46 17 10 87]


(array([0, 4, 1, 1, 1, 0, 2, 2, 3, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [122]:
# np.corrcoef
# returns pearson product-moment correlation coefficients.
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [123]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [127]:
# np.isin
# with the help  of numpy.isin() method, we can see that one array having values are checked in a different numpy array havind different elements with different sizes.
print(a)
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)
print(a[np.isin(a,items)])

[92 32 73 16 22 63 78 82 82 61 15 46 17 10 87]
[10]


In [128]:
# np.flip
# The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.
print(a)
np.flip(a)

[92 32 73 16 22 63 78 82 82 61 15 46 17 10 87]


array([87, 10, 17, 46, 15, 61, 82, 82, 78, 63, 22, 16, 73, 32, 92])

In [130]:
print(b)
np.flip(b) # by using axis we can do it column and row wise


[[35 13 30 37]
 [90 58 24 81]
 [13 33 92 16]
 [81 31 22 43]
 [39 24 24 86]
 [70 55 52 21]]


array([[21, 52, 55, 70],
       [86, 24, 24, 39],
       [43, 22, 31, 81],
       [16, 92, 33, 13],
       [81, 24, 58, 90],
       [37, 30, 13, 35]])

In [131]:
print(np.flip(b, axis=1))

[[37 30 13 35]
 [81 24 58 90]
 [16 92 33 13]
 [43 22 31 81]
 [86 24 24 39]
 [21 52 55 70]]


In [134]:
# np.put
# The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.
print(a)
np.put(a,[0,1],[110,50])
# basically put is for putting new item at the sepcific postion.


[110  50  73  16  22  63  78  82  82  61  15  46  17  10  87]
None


In [136]:
# np.delete
# The numpy.delete() function returns a new array with the help deletion of sub-arrays along the mentioned axis.
print(a)
np.delete(a,[0,2,3,4,5])

[110  50  73  16  22  63  78  82  82  61  15  46  17  10  87]


array([50, 78, 82, 82, 61, 15, 46, 17, 10, 87])

### set Functions
+ np.union1d
+ np.intersect1d
+ np.setdiff1d
+ np.setxor1d
+ np.in1d

In [141]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
print(np.union1d(m,n))
print(np.intersect1d(m,n))
print(np.setdiff1d(m,n))
print(np.setxor1d(m,n))


[1 2 3 4 5 6 7]
[3 4 5]
[1 2]
[1 2 6 7]


In [143]:
print(np.in1d(m,1))
m[np.in1d(m,1)]

[ True False False False False]


array([1])

In [144]:
# np.clip
# numpy.clip() function is used to clip (limit) the values in an array.
print(a)

[110  50  73  16  22  63  78  82  82  61  15  46  17  10  87]


In [145]:
np.clip(a,a_min=25,a_max=75)

array([75, 50, 73, 25, 25, 63, 75, 75, 75, 61, 25, 46, 25, 25, 75])